Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -41,6 +41,6 @@ jobs:
         run:  |
           echo "sleep start"
           #sleep 0.08h # Prevent to killing instance after failure
-          timeout 1H ping -i 20 www.google.com | awk '{ echo  $0"\t" }' || echo "Error: $?"
+          timeout 60m ping -i 20 www.google.com | awk '{ echo  $0"\t" }' || echo "Error: $?"
           #timeout 1.1m watch -n 20 date || echo "Error: $?"
           echo "sleep end"
